### ISSUE TITLE
Decklink 4k : video channel / consume time too high

### ISSUE THREAD

**Issue by Canigou77** [CasparCG/Server#389]
I'am working with Decklink 4K
When workfing in a 4K channel [2160p25] and playing a file (AMB or another 4K one), movie is slow. All the frames are decoded but not displayed at 25fps. Output is OK on with on the PC screen, so for me it's not a issue around performance.

In the DIAG window, with the decklink 4K channel: 
 - ffmeg : frame-time is under the half-scale. 
 - video_channel[1|2160|25] : produce_time is under the half-scale. But consume_time is upper; and very close to the top of the scale
Can you tell me what is the reason of this too high level ?

When I do the test with an HD channel on the decklink, output is correct (25 fps) and all the levels are under the half-scale.

Tested with server 2.1.0 in 64bits environnement. XEON and NVIDIA K2000.

**Comment by Canigou77** [comment]
I try the las built few minutes ago with a 4K channel output and I get always this warning:
[2015-10-29 13:27:05.964] [7968]  [warning] [diagnostics] [DeckLink 4K Pro [1-1|2160p2500]] late-frame
Even with no activity (no file playing), casparcg returns this warning.
When I play a 4K file, I get same behaviour as describe above.
What is the problem ?

**Comment by HellGore** [comment]
If you try the latest build I think that this performance problem will have been fixed.

The [warning] [diagnostics] is a new feature. It takes the vertical line events from diag that are considered negative and logs them.

**Comment by Canigou77** [comment]
I try the last build and I see the same results : late-frame are present sothing like 10 times per second for my Decklink consumer. Trace is
 [2015-10-29 17:12:16.657] [12028] [warning] [diagnostics] [DeckLink 4K Pro [1-1|2160p2500]] late-frame
I've this issue when I select a video-format > 1080 (2160p2500 for example). No need to play a file to have this trace.
In the channel diag, consume time is equal to tick time. No other error or warning when casparCG is launched. result is the same : image rate too slow.

**Comment by Canigou77** [comment]
For your information, I can build a test version and test it if needed

**Comment by HellGore** [comment]
What do you mean with a test version?

**Comment by Canigou77** [comment]
The issue with decoding a 4K file is still present. I don't know if you have a 4K borda for development or validation. I have one here. So that's why I propose to build or run test versions on my hardware.

**Comment by HellGore** [comment]
OK, I have a 4K video card, but no display hardware supporting the 6G SDI signal. I have a DeckLink 4k Extreme 6G which is only a PCIe 4X card, but yours is a 8X card. Have you verified that you are getting the PCI-lanes required?

**Comment by Canigou77** [comment]
Here are the slots of my machines :+
1  PCI-E 3.0 (x16) Full-height (16.5" length)
1 PCI-E 3.0 (x16) Full-height (10" length)
1 PCI-E 3.0 (x8) Full-height (16.5" length)
1 PCI-E 3.0 (x8) Full-height (6.6" length)
2 PCI-E 3.0 (x8) Low-profile (6.6" length)
What is your opinion ?
I can change the slot for a test in the afternoon ...  

Note that I can decode a file with 64bits directshow filters on the 4K output without the issue.

**Comment by Canigou77** [comment]
Do you know and to send you a screenshot ont hsi github ?

**Comment by HellGore** [comment]
Do you have a dual CPU motherboard and two CPU:s installed? Otherwise I think that some of those PCI-E ports will be less than x8 electrically in some configurations.

**Comment by Canigou77** [comment]
Yes, 2 CPUs installed.

**Comment by Canigou77** [comment]
I've changed the slot of the decklink to a slot managed by CPU1: same behaviour in casparCG : 10 late-frame per second in a 4K channel.

**Comment by Canigou77** [comment]
For intormation:
when the video_channel is HD (1080p2500): in the video_channel diag: consume time is 0 and tick-time is always the half-scale
When 2160 is configued I get a tick-frame not constant. see hardcopies
![1080](https://cloud.githubusercontent.com/assets/15155076/10850440/04a5fec0-7f26-11e5-8412-5e6a9032abc0.png)
![2160](https://cloud.githubusercontent.com/assets/15155076/10850447/09fc26d8-7f26-11e5-8bc1-8f490b24f24f.png)

**Comment by Canigou77** [comment]
Seems to be better with the last beta. I continue my tests.

**Comment by Canigou77** [comment]
OK for me. I close the issue.
